@startuml send_push
!theme gematik from ../puml

actor "FdV" as App
entity "Fachdienst" as Fachdienst
entity "Push Gateway" as NotificationService
entity "Apple/Google" as NotificationProvider

group SendPush
    Fachdienst -> Fachdienst : event_trigger
    activate Fachdienst
    Fachdienst -> Fachdienst : encrypt_message
    Fachdienst -> NotificationService : **POST** //push/v1/notify//
    activate NotificationService
    NotificationService -->> Fachdienst : status
    deactivate Fachdienst
    NotificationService -> NotificationProvider : send_push
    deactivate NotificationService

    activate NotificationProvider
    NotificationProvider -> App : push
    deactivate NotificationProvider

    activate App
    App -> App : decrypt_notification
    App -> App : show_notification
end
deactivate App

@enduml
