@startuml Registration

actor "FdV" as App
entity "FD (EPA/TIM/ERP)" as Fachdienst
entity "Push Gateway" as NotificationService
entity "Apple/Google" as NotificationProvider

group Registration
    activate App
    App -> NotificationProvider : get_push_token
    activate NotificationProvider
    NotificationProvider -->> App : push_token
    deactivate NotificationProvider
    App -> App : create_app_id
    App -> App : create encryption keypair
    App -> Fachdienst : register_app(\n\taccess_token,\n\tGatewayID?,\n\tapp_infos=(app_id, push_token, platform, enc_key),\n\toptional[channels]\n)
    activate Fachdienst
    Fachdienst -> Fachdienst : store information
    Fachdienst -->> App : status
    deactivate Fachdienst
    deactivate App
end

@enduml
